import type { ModelConfig } from '@/types';
import type { AgenticCostResult, WorkloadUnit } from '@/lib/calculator';
import { formatCost } from '@/lib/tokens';

interface ScenarioRow {
  key: string;
  label: string;
  result: AgenticCostResult;
}

export interface ExportData {
  modelName: string;
  modelId: string;
  provider: string;
  inputs: {
    unit: WorkloadUnit;
    requestsPerMonth: number;
    tasksPerMonth: number;
    llmCallsPerTask: number;
    inputTokens: number;
    outputTokens: number;
    cachingEnabled: boolean;
    cachedPct: number;
    batchEnabled: boolean;
    batchFactor: number;
  };
  scenarios: {
    key: string;
    label: string;
    monthlyCost: number;
    costPerCall: number;
  }[];
  uncertainty: {
    multipliers: { low: number; mid: number; high: number };
    costs: { low: number; mid: number; high: number };
  } | null;
  generatedAt: string;
}

export function buildExportData(
  model: ModelConfig,
  scenarios: { rows: readonly ScenarioRow[]; selected: AgenticCostResult },
  uncertainty: { multipliers: { low: number; mid: number; high: number }; costs: { low: number; mid: number; high: number } } | null,
  inputs: {
    unit: WorkloadUnit;
    requestsPerMonth: number;
    tasksPerMonth: number;
    llmCallsPerTask: number;
    inputTokens: number;
    outputTokens: number;
    cachingEnabled: boolean;
    cachedPct: number;
    batchEnabled: boolean;
    batchFactor: number;
  },
): ExportData {
  return {
    modelName: model.name,
    modelId: model.id,
    provider: model.provider,
    inputs,
    scenarios: scenarios.rows.map((r) => ({
      key: r.key,
      label: r.label,
      monthlyCost: r.result.perMonth.totalCost,
      costPerCall: r.result.perCall.totalCost,
    })),
    uncertainty,
    generatedAt: new Date().toISOString(),
  };
}

export function exportAsJSON(data: ExportData): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `trim-${data.modelId}-estimate.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportAsMarkdown(data: ExportData): Promise<void> {
  const lines: string[] = [];
  lines.push(`## AI Cost Estimate — ${data.modelName} (${data.provider})`);
  lines.push('');

  const volume = data.inputs.unit === 'requests'
    ? `${data.inputs.requestsPerMonth.toLocaleString()} requests/mo`
    : `${data.inputs.tasksPerMonth.toLocaleString()} tasks/mo · ${data.inputs.llmCallsPerTask} calls/task`;

  lines.push(`**Inputs:** ${volume} · ${data.inputs.inputTokens} in · ${data.inputs.outputTokens} out`);
  lines.push(
    `**Modifiers:** Caching ${data.inputs.cachingEnabled ? `on (${data.inputs.cachedPct}%)` : 'off'} · Batch ${data.inputs.batchEnabled ? `on (×${data.inputs.batchFactor})` : 'off'}`,
  );
  lines.push('');

  lines.push('| Scenario | Monthly Cost | Cost/Call |');
  lines.push('|----------|-------------|-----------|');
  for (const s of data.scenarios) {
    lines.push(`| ${s.label} | ${formatCost(s.monthlyCost)} | ${formatCost(s.costPerCall)} |`);
  }

  if (data.uncertainty) {
    lines.push('');
    lines.push(`**Agentic overhead range:** ×${data.uncertainty.multipliers.low} ${formatCost(data.uncertainty.costs.low)} · ×${data.uncertainty.multipliers.mid} ${formatCost(data.uncertainty.costs.mid)} · ×${data.uncertainty.multipliers.high} ${formatCost(data.uncertainty.costs.high)}`);
  }

  lines.push('');
  lines.push('*Generated by Trim Playground*');

  await navigator.clipboard.writeText(lines.join('\n'));
}

export async function exportAsPNG(element: HTMLElement, modelId: string): Promise<void> {
  const { default: html2canvas } = await import('html2canvas-pro');
  const canvas = await html2canvas(element, { backgroundColor: null });
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `trim-${modelId}-estimate.png`;
    a.click();
    URL.revokeObjectURL(url);
  });
}
