'use client';

import { useState } from 'react';
import { formatCost } from '@/lib/tokens';
import type { EnrichedEstimate } from '@/lib/estimate-calculator';
import type { SampleResultV2 } from '@/types';

interface PlaygroundExportButtonsProps {
  mode: 'estimate' | 'sample';
  estimates: EnrichedEstimate[] | null;
  sampleResults: SampleResultV2[] | null;
  requestsPerMonth: number;
  resultsRef: React.RefObject<HTMLDivElement | null>;
}

function buildPlaygroundData(props: PlaygroundExportButtonsProps) {
  const { mode, estimates, sampleResults, requestsPerMonth } = props;

  if (mode === 'estimate' && estimates) {
    return {
      mode: 'estimate' as const,
      requestsPerMonth,
      models: estimates.map((e) => ({
        modelId: e.modelId,
        modelName: e.modelName,
        provider: e.provider,
        inputTokens: e.breakdown.input.tokens,
        inputCost: e.breakdown.input.cost,
        perRequest: { min: e.total.min, median: e.total.median, max: e.total.max },
        monthlyCost: { min: e.monthlyCost.min, median: e.monthlyCost.median, max: e.monthlyCost.max },
      })),
      generatedAt: new Date().toISOString(),
    };
  }

  if (mode === 'sample' && sampleResults) {
    return {
      mode: 'sample' as const,
      requestsPerMonth,
      models: sampleResults.map((r) => ({
        modelId: r.modelId,
        modelName: r.modelName,
        provider: r.provider,
        inputTokens: r.actualUsage.inputTokens,
        outputTokens: r.actualUsage.outputTokens,
        actualCost: r.actualCost,
        latencyMs: r.latencyMs,
        monthlyCost: r.actualCost * requestsPerMonth,
      })),
      generatedAt: new Date().toISOString(),
    };
  }

  return null;
}

function buildMarkdown(props: PlaygroundExportButtonsProps): string {
  const { mode, estimates, sampleResults, requestsPerMonth } = props;
  const lines: string[] = [];

  if (mode === 'estimate' && estimates && estimates.length > 0) {
    lines.push('## Trim Playground — Estimate Comparison');
    lines.push('');
    lines.push(`**Requests/month:** ${requestsPerMonth.toLocaleString()}`);
    lines.push('');
    lines.push('| Model | Provider | Per Request | Monthly Cost |');
    lines.push('|-------|----------|------------|-------------|');
    for (const e of estimates) {
      lines.push(`| ${e.modelName} | ${e.provider} | ${formatCost(e.total.median)} | ${formatCost(e.monthlyCost.median)} |`);
    }
  } else if (mode === 'sample' && sampleResults && sampleResults.length > 0) {
    lines.push('## Trim Playground — Sample Comparison');
    lines.push('');
    lines.push(`**Requests/month:** ${requestsPerMonth.toLocaleString()}`);
    lines.push('');
    lines.push('| Model | Provider | Cost | Latency | Input | Output | Est. Monthly |');
    lines.push('|-------|----------|------|---------|-------|--------|-------------|');
    for (const r of sampleResults) {
      const monthly = r.actualCost * requestsPerMonth;
      lines.push(`| ${r.modelName} | ${r.provider} | ${formatCost(r.actualCost)} | ${r.latencyMs}ms | ${r.actualUsage.inputTokens} | ${r.actualUsage.outputTokens} | ${formatCost(monthly)} |`);
    }
  }

  lines.push('');
  lines.push('*Generated by Trim Playground*');
  return lines.join('\n');
}

const btnBase =
  'px-3 py-1.5 rounded-lg border border-foreground/15 text-xs font-bold uppercase tracking-wider text-foreground/70 hover:text-foreground hover:border-foreground/30 transition-colors';

export function PlaygroundExportButtons(props: PlaygroundExportButtonsProps) {
  const [copied, setCopied] = useState(false);

  async function handleMarkdown() {
    const md = buildMarkdown(props);
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleJSON() {
    const data = buildPlaygroundData(props);
    if (!data) return;
    const json = JSON.stringify(data, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `trim-playground-${data.mode}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handlePNG() {
    if (!props.resultsRef.current) return;
    const { default: html2canvas } = await import('html2canvas-pro');
    const canvas = await html2canvas(props.resultsRef.current, { backgroundColor: null });
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `trim-playground-${props.mode}.png`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }

  return (
    <div className="flex gap-2">
      <button type="button" onClick={handleMarkdown} className={btnBase}>
        {copied ? 'Copied!' : 'Markdown'}
      </button>
      <button type="button" onClick={handlePNG} className={btnBase}>
        PNG
      </button>
      <button type="button" onClick={handleJSON} className={btnBase}>
        JSON
      </button>
    </div>
  );
}
